# Generated by Django 3.0.7 on 2023-01-13 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0005_auto_20230112_1902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='available_units',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.FloatField(),
        ),
    ]
